server.port=8080
spring.application.name=api-gateway-service

# =========================
# Gateway actuator (optional)
# =========================
management.endpoints.web.exposure.include=gateway
management.endpoint.gateway.enabled=true


# =========================
# Market Data (Fetcher)
# =========================
spring.cloud.gateway.routes[0].id=market-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/market/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/market/(?<segment>.*), /internal/market/${segment}


# =========================
# Stock Query Service
# =========================
spring.cloud.gateway.routes[1].id=stock-query
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/query/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/query/(?<segment>.*), /internal/query/${segment}


# =========================
# Search Service
# =========================
spring.cloud.gateway.routes[2].id=stock-search
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/search/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/search/(?<segment>.*), /internal/search/${segment}

# =========================
# Stream Service (WebSocket / SSE)
# =========================
spring.cloud.gateway.routes[3].id=stock-stream
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/stream/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/stream/(?<segment>.*), /api/stream/${segment}
